package guilda;

public class JFrameRPG extends javax.swing.JFrame {

    private Logic l;
    private Guerreiro w;
    private Arqueiro a;
    private Mago m;
    private int index;
    
    public JFrameRPG() {
        l = new Logic();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Senha");

        jLabel3.setText("Experiência");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Classe");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guerreiro", "Arqueiro", "Mago" }));

        jLabel5.setText("Dinheiro");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Data/Fim");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Data/Inicio");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTable1.setModel(
            new javax.swing.table.DefaultTableModel(
                new Object [][]
                {
                },
                new String []
                {
                    "Login", "Senha", "Experiência", "Dinheiro", "Dano Máximo", "Dano Mínimo", "Classe"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane1.setViewportView(jTable1);
            jTable1.getAccessibleContext().setAccessibleName("");

            jButton1.setText("Inserir");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("Remover");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton3.setText("Alterar");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jButton4.setText("Limpar");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jPasswordField1ActionPerformed(evt);
                }
            });

            jLabel8.setText("Login");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(468, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addGap(102, 102, 102))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addComponent(jButton3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel8))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)
                                    .addGap(197, 197, 197))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)
                                    .addGap(27, 27, 27)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(142, 142, 142))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))))
                    .addContainerGap(80, Short.MAX_VALUE))
            );

            jButton1.getAccessibleContext().setAccessibleName("buttonInsert");
            jButton2.getAccessibleContext().setAccessibleName("buttonRemove");
            jButton3.getAccessibleContext().setAccessibleName("buttonChange");
            jButton4.getAccessibleContext().setAccessibleName("buttonClear");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s = (String) jComboBox1.getSelectedItem();
        if(s.contains("Guerreiro"))
        {
            w = new Guerreiro();
            w.setLogin(jTextField1.getText());
            w.setPassword(jPasswordField1.getPassword());
            w.setExperience(Integer.parseInt(jTextField3.getText()));
            w.setMoney(Integer.parseInt(jTextField4.getText()));
            w.setMaxDamage(Integer.parseInt(jTextField5.getText()));
            w.setMinDamage(Integer.parseInt(jTextField6.getText()));
            w.setClasse("Guerreiro");
            l.addGuerreiro(w);
            
            addLinha(0);
        }
        else if(s.contains("Arqueiro"))
        {
            a = new Arqueiro();
            a.setLogin(jTextField1.getText());
            a.setPassword(jPasswordField1.getPassword());
            a.setExperience(Integer.parseInt(jTextField3.getText()));
            a.setMoney(Integer.parseInt(jTextField4.getText()));
            a.setMaxDamage(Integer.parseInt(jTextField5.getText()));
            a.setMinDamage(Integer.parseInt(jTextField6.getText()));
            a.setClasse("Arqueiro");
            l.addArqueiro(a);
            
            addLinha(1);
        }
        else
        {
            m = new Mago();
            m.setLogin(jTextField1.getText());
            m.setPassword(jPasswordField1.getPassword());
            m.setExperience(Integer.parseInt(jTextField3.getText()));
            m.setMoney(Integer.parseInt(jTextField4.getText()));
            m.setMaxDamage(Integer.parseInt(jTextField5.getText()));
            m.setMinDamage(Integer.parseInt(jTextField6.getText()));
            m.setClasse("Mago");
            l.addMago(m);
            
            addLinha(2);
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void addLinha(int y)
    {
        javax.swing.table.DefaultTableModel d = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        
        if(y == 0)
        {   
            d.addRow(new Object[]{w.getLogin(),
                                  w.getPassword(),
                   String.valueOf(w.getExperience()),
                   String.valueOf(w.getMoney()),
                   String.valueOf(w.getMaxDamage()),
                   String.valueOf(w.getMinDamage()),
                                  w.getClasse()});
        }
        else if(y == 1)
        {
            d.addRow(new Object[]{a.getLogin(),
                                  a.getPassword(),
                   String.valueOf(a.getExperience()),
                   String.valueOf(a.getMoney()),
                   String.valueOf(a.getMaxDamage()),
                   String.valueOf(a.getMinDamage()),
                                  a.getClasse()});

        }
        else if(y == 2)
        {      
            d.addRow(new Object[]{m.getLogin(),
                                  m.getPassword(),
                   String.valueOf(m.getExperience()),
                   String.valueOf(m.getMoney()),
                   String.valueOf(m.getMaxDamage()),
                   String.valueOf(m.getMinDamage()),
                                  m.getClasse()});
        }
    }
    
    public boolean removeLinha(int y)
    {
        javax.swing.table.DefaultTableModel d = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        
        String p = jTextField2.getText();
        
        if(y == 0)
        {   
            index = 0;
            for(Guerreiro x : l.getListW())
            {
                if(p.equals(x.getLogin()))
                {
                    d.removeRow(index);
                    l.removeGuerreiro(x);
                    System.out.println(l.getListW().size());
                    return true;
                }
                index++;
            }
        }
        else if(y == 1)
        {
            index = 0;
            for(Arqueiro x : l.getListA())
            {
                if(p.equals(x.getLogin()))
                {
                    d.removeRow(index);
                    l.removeArqueiro(x);
                    System.out.println(l.getListA().size());
                    return true;
                }
                index++;
            }
        }
        else if(y == 2)
        {      
            index = 0;
            for(Mago x : l.getListM())
            {
                if(p.equals(x.getLogin()))
                {
                    d.removeRow(index);
                    l.removeMago(x);
                    System.out.println(l.getListM().size());
                    return true;
                }
                index++;
            }
        }
        return false;
    }
    
    public void alteraLinha(int y)
    {
        javax.swing.table.DefaultTableModel d = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        
        String p = jTextField1.getText();
        
        if(y == 0)
        {   
            index = 0;
            for(Guerreiro x : l.getListW())
            {
                if(p.equals(x.getLogin()))
                {
                    x.setPassword(jPasswordField1.getPassword());
                    x.setExperience(Integer.parseInt(jTextField3.getText()));
                    x.setMoney(Integer.parseInt(jTextField4.getText()));
                    x.setMaxDamage(Integer.parseInt(jTextField5.getText()));
                    x.setMinDamage(Integer.parseInt(jTextField6.getText()));
                    d.removeRow(index);
                    d.addRow(new Object[]{x.getLogin(),
                                          x.getPassword(),
                           String.valueOf(x.getExperience()),
                           String.valueOf(x.getMoney()),
                           String.valueOf(x.getMaxDamage()),
                           String.valueOf(x.getMinDamage()),
                                          x.getClasse()});
                    System.out.println(l.getListW().size());
                    break;
                }
                index++;
            }
        }
        else if(y == 1)
        {
            index = 0;
            for(Arqueiro x : l.getListA())
            {
                if(p.equals(x.getLogin()))
                {
                    x.setPassword(jPasswordField1.getPassword());
                    x.setExperience(Integer.parseInt(jTextField3.getText()));
                    x.setMoney(Integer.parseInt(jTextField4.getText()));
                    x.setMaxDamage(Integer.parseInt(jTextField5.getText()));
                    x.setMinDamage(Integer.parseInt(jTextField6.getText()));
                    d.removeRow(index);
                    d.addRow(new Object[]{x.getLogin(),
                                          x.getPassword(),
                           String.valueOf(x.getExperience()),
                           String.valueOf(x.getMoney()),
                           String.valueOf(x.getMaxDamage()),
                           String.valueOf(x.getMinDamage()),
                                          x.getClasse()});
                    System.out.println(l.getListA().size());
                    break;
                }
                index++;
            }
        }
        else if(y == 2)
        {      
            index = 0;
            for(Mago x : l.getListM())
            {
                if(p.equals(x.getLogin()))
                {
                    x.setPassword(jPasswordField1.getPassword());
                    x.setExperience(Integer.parseInt(jTextField3.getText()));
                    x.setMoney(Integer.parseInt(jTextField4.getText()));
                    x.setMaxDamage(Integer.parseInt(jTextField5.getText()));
                    x.setMinDamage(Integer.parseInt(jTextField6.getText()));
                    d.removeRow(index);
                    d.addRow(new Object[]{x.getLogin(),
                                          x.getPassword(),
                           String.valueOf(x.getExperience()),
                           String.valueOf(x.getMoney()),
                           String.valueOf(x.getMaxDamage()),
                           String.valueOf(x.getMinDamage()),
                                          x.getClasse()});
                    System.out.println(l.getListM().size());
                    break;
                }
                index++;
            }
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(removeLinha(0) == true);
        else if(removeLinha(1) == true);
        else if(removeLinha(2) == true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s = (String) jComboBox1.getSelectedItem();
        if(s.contains("Guerreiro"))
            alteraLinha(0);
        else if(s.contains("Arqueiro"))
            alteraLinha(1);
        else
            alteraLinha(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText("");
        jPasswordField1.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText(""); 
    }//GEN-LAST:event_jButton4ActionPerformed

private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameRPG().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
